Algoritmo "exercicio5"

Var
p:inteiro


Inicio
Escreva ("Digite a pontuação da sua prova: ")
Leia (p)
se (p >= 0) e (p <=30) entao
 Escreva ("REGULAR")
 senao
se (p >= 31) e (p <= 60) entao
 escreva ("BOM")
senao
se (p >=61) e (p <= 90) entao
escreva ("MUITO BOM")
senao
se (p >= 91) e (p <= 100) entao
 escreva ("ÓTIMO")
senao
 escreva ("Pontuação inválida")
fimse
fimse
fimse
fimse
Fimalgoritmo