Algoritmo "exemplo11"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/05/2020
Var
n,soma:real

Inicio
soma <- 0
n<- 0
repita
soma<- soma +n
escreva("Digite um numero: ")
leia (n)
ate (n<0)
escreva ("soma total: ",soma)
Fimalgoritmo